# !!! DO NOT CHANGE THE FOLLOWING SETTINGS IF YOU DONT KNOW WHAT THEY ARE !!!

log:
  datetime: ""
  log_record: ""

session:
  session_record: ""
  session_info: ""

error_handle:
  login_errors:
    - error_code: 200
      hint_message: "登录成功"
      log_message: "Login success"
    - error_code: 33
      hint_message: "账号被冻结，可能是您的账号产生了异常流量，请联系运维人员并提供运行日志"
      log_message: "Account is frozen"
    - error_code: 39
      hint_message: "在线设备数已达到上限，请手动下线设备或开启自动下线配置"
      log_message: "Session concurrency overload"
    - error_code: 49
      hint_message: "当前账号只可使用访客网络"
      log_message: "Only guest network is available"
    - error_code: 60
      hint_message: "配置文件中设置的用户名和密码不正确"
      log_message: "Invalid username or password"
      # default
    - error_code: -1
      hint_message: "其它错误，请联系运维人员并提供运行日志"
      log_message: "Error happens when logging in"
  logout_errors:
    - error_code: 200
      hint_message: "下线成功"
      log_message: "Logout success"
      # default
    - error_code: -1
      hint_message: "下线失败"
      log_message: "Logout failed"
  get_session_errors:
    - error_code: 200
      hint_message: "获取会话列表成功"
      log_message: "Get session list success"
      # default
    - error_code: -1
      hint_message: "获取会话列表失败"
      log_message: "Get session list failed"
  internet_check_errors:
    - error_code: 200
      hint_message: "已经成功登录"
      log_message: "Already logged in"
      # default
    - error_code: -1
      hint_message: "还未登陆"
      log_message: "Currently logged out"
  intranet_check_errors:
    - error_code: 200
      hint_message: "认证服务器可用"
      log_message: "Portal server is available"
      # default
    - error_code: -1
      hint_message: "认证服务器不可用"
      log_message: "Portal server is unavailable"