online:
    auth_data:
        domain: xjtu
        username: zhangsan
        password: "123456789"
device:
    known_mac_list: ['11:22:33:44:55:66', 'aa:bb:cc:dd:ee:ff']
    use_interface: true
session:
    portal:
        auto_logout: true
logger:
    output_writer: [stdout, file]
    level: WARNING
    file_path: run.log
    color: true
ui:
    mode: interact
